

namespace Blaze.Manage.Csv.Enum
{
    public enum AnalysisPoint
    {
        GameStart = 1,
        LoadingPage = 2,
        EnterSuccess = 3,
        GameEnd = 4,
        SigninEnter = 5,
        SigninAppend = 6,
        Signing = 7,
        DecorateEnter = 8,
        DecorateSwitch = 9,
        DecorateShopBuy = 10,
        DecorateShopBuySuccess = 11,
        DecorateShopBuyFail = 12,
        DecorateUseItem = 13,
        DecorateRemoveItem = 14,
        DrawEnter = 15,
        DrawOne = 16,
        DrawTen = 17,
        ChargeEnter = 18,
        ChapterPlay = 19,
        ChapterPlaySuccess = 20,
        ChapterPlayFail = 21,
        PhotoEnter = 22,
        PhotoView = 23,
        Phone = 24,
        PhoneFriendMoment = 25,
        ThumbsUp = 26,
        Comments = 27,
        PhoneViewChat = 28,
        MobilePhone = 29,
        LikeEnter = 30,
        Version = 31,
        SetEnter = 32,
        SetCloseMusic = 33,
        SetCloseSound = 34,
        SetNightSwitch = 35,
        ChooseChapter2JJ = 36,
        ChooseChapter2ZY = 37,
        ChooseChapter2YS = 38,
        ChooseChapter4JJ = 39,
        ChooseChapter4ZY = 40,
        ChooseChapter4YS = 41,
        Chapter2BestHeart = 42,
        Chapter3BestHeart = 43,
        Chapter4BestHeart = 44,
        Chapter5BestHeart = 45,
        Chapter6BestHeart = 46
    }
}
