

namespace Blaze.Manage.Csv.Enum
{
    public enum AnPoint
    {
        start_logo = 1,
        start_backgroundPic = 2,
        start_loginbtn = 3,
        start_login_method = 4,
        start_SDK_post = 5,
        start_SDK_get = 6,
        start_login = 7,
        start_loading = 8,
        enroll_method = 9,
        enroll_SDK_post = 10,
        enroll_SDK_get = 11,
        enroll_state_register = 12,
        guide_id = 13,
        guide_state = 14,
        get_Petal_num = 15,
        get_Petal_method = 16,
        get_Petal_result = 17,
        cost_Petal_num = 18,
        cost_Petal_method = 19,
        cost_Petal_result = 20,
        get_Furniture_num = 21,
        get_Furniture_method = 22,
        get_Furniture_result = 23,
        get_Firework_num = 24,
        get_Firework_method = 25,
        get_Firework_result = 26,
        get_Chapter_num = 27,
        get_Chapter_method = 28,
        get_Chapter_result = 29,
        get_Sculpt_num = 30,
        get_Sculpt_method = 31,
        get_Sculpt_result = 32,
        get_Key_num = 33,
        get_Key_method = 34,
        get_Key_result = 35,
        get_HeartChapter_num = 36,
        get_HeartChapter_method = 37,
        get_HeartChapter_result = 38,
        get_Coins_num = 39,
        get_Coins_method = 40,
        get_Coins_result = 41,
        get_Caricature_num = 42,
        get_Caricature_method = 43,
        get_Caricature_result = 44,
        sign_click_days = 47,
        sign_click_today = 48,
        Chapter_click_lack = 49,
        Chapter_click_failed = 50,
        Chapter_pass = 51,
        Chapter_pass_failed = 52,
        Lottery_proportion = 53,
        Lottery_today_one = 54,
        Lottery_today_ten = 55,
        Lottery_today_reward = 56,
        Firework_proportion = 57,
        Achievement_record = 58,
        Achievement_today_record = 59,
        Atask_id = 60,
        ChapterBestHeart = 61,
        role_Best_Heart = 62,
        Dress_record = 63,
        procurement_today_record = 64,
        procurement_click_lack = 65,
        procurement_click_failed = 66,
        procurement_pass_failed = 67
    }
}
